### ISSUE TITLE
Iteration #2

### ISSUE THREAD

**Issue by jedrzej** [jedrzej/world-map#4]
# Acceptance criteria
- Schema and validation rules are defined and enforced for all models
 - User
 - Organization
 - Team
- API allows CRUD operations on User, Organization and Team models
- API allows linking/unlinking users, organizations and teams
- API provides read-only endpoint for fetching static content
- Integration tests exist for API endpoints and allowed operations
 -  example scenarios where NodeJS applications can become fragile have been described, automated tests to mitigate this have been implemented
- available tools for implementing automated integrated tests for NodeJS application have been researched and learnings have been documented
- pain-points of using node-rest-client library for communication with backend and ways to overcome the issues (alternative client libraries, better way of using currently used client library) have been documented

**Comment by joshwnj** [comment]
Looking good!

A couple of things before this is approved:
- What do you think about removing the Additional Goals heading, and including those points under Acceptance Criteria as well?  I think these are an important part of the delivery.
- I'd like to see the "automated tests" item become a bit more specific. Something like "demonstrate some scenarios where NodeJS applications can become fragile, and how we can use automated tests to mitigate this"

**Comment by jedrzej** [comment]
@joshwnj done

**Comment by joshwnj** [comment]
:+1: looks good - go for it :)

**Comment by jedrzej** [comment]
I've created a milestone and moved acceptance criteria there
